name: health_sync_question
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  shimmer: 3.0.0
  file_picker: ^10.3.3
  url_launcher: 6.3.2
  image_picker: ^1.2.1
  image_cropper: ^9.1.0
  android_intent_plus: 6.0.0
  flutter_cache_manager: 3.4.1
  intl: 0.20.2
  mobkit_dashed_border: ^0.0.8
  flutter:
    sdk: flutter

  network:
    git:
      url: git@vcs.technonext.com:TechnoNext/mobile-apps/airapps-commons/netword.git
      ref: v0.0.14

  common:
    git:
      url: git@vcs.technonext.com:TechnoNext/mobile-apps/airapps-commons/common.git
      ref: v0.0.7

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  google_fonts: ^6.3.2
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_flavorizr: 2.4.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/